### ISSUE TITLE
FIFO is not bounded

### ISSUE THREAD

**Issue by dapplion** [alanshaw/it-pushable#31]
FIFO datastructure appears to not have an upper bound on data it can hold. This can blow up applications, and should have a customizable parameter "maxSize" or related

**Comment by achingbrain** [comment]
Should be simple enough now, since https://github.com/alanshaw/it-pushable/pull/27 added a notion of a `readableLength`

**Comment by dapplion** [comment]
> Should be simple enough now, since #27 added a notion of a `readableLength`

Are you aware of consistent usage of such pattern across all js-libp2p packages?

**Comment by achingbrain** [comment]
Not exactly but it sounds similar to the [highWaterMark](https://nodejs.org/api/stream.html#buffering) concept in node streams or perhaps [ByteLengthQueuingStrategy](https://developer.mozilla.org/en-US/docs/Web/API/ByteLengthQueuingStrategy/ByteLengthQueuingStrategy)/[CountQueuingStrategy](https://developer.mozilla.org/en-US/docs/Web/API/CountQueuingStrategy) in whatwg streams.

I guess really the question is when the high water mark is reached, should the pushable throw, should it wait for space in the FIFO queue or should it flag it's status in some other way?

Node does not enforce a limit, that is, you can keep writing data after the hwm is reached.  When the return value of `writable.write` is `false`, the hwm has been reached and you should wait for the `drain` event before writing more data.

whatwg streams don't enforce the limit either, instead the value of [controller.desiredSize](https://streams.spec.whatwg.org/#rs-default-controller-desired-size) becomes negative when the hwm is reached.

On that basis we should not prevent pushing new data to the FIFO but set a flag or similar.  That flag can be interrogated by consumers.

In `@libp2p/mplex` we already do something similar by [reading the `readableLength` to see if we should push new data or not](https://github.com/libp2p/js-libp2p-mplex/blob/master/src/mplex.ts#L286-L298) - this flag would be consulted instead of the `readableLength`.

What do you think?

**Comment by dapplion** [comment]
Agree this is very largely dependent on the consumer of the it-pushable library. With readableLength available all the approaches you may want to implement are possible, so closing the issue here.
